# Generated by Django 4.2.7 on 2023-12-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_hashtag_comment_product_hashtag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='Category',
        ),
    ]
