# Generated by Django 4.2.7 on 2023-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_hashtag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='post.category'),
        ),
    ]
