# Generated by Django 4.2.7 on 2023-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reviews',
            field=models.ManyToManyField(blank=True, related_name='product_reviews', to='post.review'),
        ),
    ]
